---
- name: Read current configuration
  no_log: true
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.slurp:
    path: "{{ dss_config_connections_json_path }}"
  register: dss_config_connections_json_raw

- name: Set connections variable
  no_log: true
  ansible.builtin.set_fact:
    dss_connections_config_json: "{{ dss_config_connections_json_raw.content | b64decode | from_json }}"
    dss_connections_gcs_config:
      connections:
        GCS:
          params:
            authType: KEYPAIR
            projectId: "candidate-emea-jeilander "
            appSecretContent: "{{ dss_gcs_private_key | string }}"
            defaultManagedBucket: "{{ dss_gcs_bucket_name }}"
            defaultManagedPath: "{{ dss_gcs_managed_path }}"
            hdfsInterface: NONE
            metastoreSynchronizationMode: NO_SYNC
            namingRule: {}
            dkuProperties: []
          type: GCS
          creationTag:
            versionNumber: 0
            lastModifiedBy:
              login: admin
            lastModifiedOn: 1648311293761
          allowWrite: true
          allowManagedDatasets: true
          allowManagedFolders: true
          useGlobalProxy: false
          maxActivities: 0
          customFields: {}
          credentialsMode: GLOBAL
          customBasicConnectionCredentialProviderParams: []
          usableBy: ALL
          allowedGroups: []
          detailsReadability:
            readableBy: NONE
            allowedGroups: []
          indexingSettings:
            indexIndices: false
            indexForeignKeys: false
            indexSystemTables: false

- name: Set fact
  no_log: true
  ansible.builtin.set_fact:
    dss_config_merged_connections_json: "{{ dss_connections_config_json | combine (dss_connections_gcs_config, recursive=true) }}"

- name: Copy over connections.json
  no_log: true
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.copy:
    dest: "{{ dss_config_connections_json_path }}"
    backup: true
    content: "{{ dss_config_merged_connections_json | to_nice_json }}"
    mode: 0644
  notify: restart_dss
