---
- name: Download DSS
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.get_url:
    url: "{{ dss_cdn_url }}/{{ dss_version }}/{{ item }}.tar.gz"
    dest: "{{ dss_install_target_dir }}/{{ item }}.tar.gz"
    mode: 0660
  loop:
    - "dataiku-dss-{{ dss_version }}"
    - "dataiku-dss-hadoop-standalone-libs-generic-hadoop3-{{ dss_version }}"
    - "dataiku-dss-spark-standalone-{{ dss_version }}-{{ dss_spark_version }}-generic-hadoop3"

- name: Unarchive DSS
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.unarchive:
    src: "{{ dss_install_target_dir }}/{{ item }}.tar.gz"
    dest: "{{ dss_install_target_dir }}"
    creates: "{{ dss_install_target_dir }}/{{ item }}"
    remote_src: true
  loop:
    - "dataiku-dss-{{ dss_version }}"

- name: Install DSS dependencies
  become: true
  ansible.builtin.shell:
    cmd: >-
      {{ dss_install_script_dir }}/install-deps.sh -yes 2>&1 > /tmp/dss-install-deps.log
      &&
      touch {{ dss_install_script_dir }}/DEPS-INSTALLED
    creates: "{{ dss_install_script_dir }}/DEPS-INSTALLED"

- name: Run Installer
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.shell:
    cmd: >-
      {{ dss_install_dir }}/installer.sh
      -d {{ dss_data_dir }}
      -p {{ dss_webui_port }}
      -P python{{ dss_python_default_version }}
      &&
      touch {{ dss_install_target_dir }}/INSTALLED
    creates: "{{ dss_install_target_dir }}/INSTALLED"

- name: Install Dataiku python API
  become: true
  ansible.builtin.pip:
    executable: "{{ dss_pip_path }}"
    name: "{{ item }}"
    state: present
  loop: "{{ dss_pip_additional_packages }}"

- name: Place licence file
  no_log: true
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.copy:
    dest: "{{ dss_config_license_path }}"
    mode: 0622
    content: "{{ dss_license_json }}"

- name: Run boot
  become: true
  ansible.builtin.command:
    cmd: >-
      {{ dss_install_script_dir }}/install-boot.sh
      {{ dss_data_dir }}
      {{ dss_service_username }}
    creates: "/etc/init.d/{{ dss_systemd_service_name }}"

- name: Enable and start DSS service
  become: true
  ansible.builtin.systemd:
    name: "{{ dss_systemd_service_name }}"
    state: started
    enabled: true

- name: Install Hadoop integration
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.command:
    cmd: >-
      {{ dss_dssadmin_path }} install-hadoop-integration
      -standaloneArchive {{ dss_install_target_dir }}/dataiku-dss-hadoop-standalone-libs-generic-hadoop3-{{ dss_version }}.tar.gz
    creates: "{{ dss_env_hadoop_path }}"

- name: Install Spark integration
  become: true
  become_user: "{{ dss_service_username }}"
  ansible.builtin.command:
    cmd: >-
      {{ dss_dssadmin_path }} install-spark-integration
      -standaloneArchive {{ dss_install_target_dir }}/dataiku-dss-spark-standalone-{{ dss_version }}-3.1.2-generic-hadoop3.tar.gz
      -forK8S
    creates: "{{ dss_env_spark_path }}"
