---
- name: "[DNS] - Update dataiku.azorion.com record"
  ansible.builtin.uri:
    url: "{{ dss_leaseweb_dns_api_endpoint }}/{{ dss_public_fqdn.split('.')[-2:] | join('.')  }}/resourceRecordSets/{{ dss_public_fqdn }}./A"
    method: PUT
    body_format: json
    headers:
      x-lsw-auth: "{{ dss_leaseweb_api_key }}"
    body:
      content:
        - "{{ dss_public_proxy_ip }}"
      ttl: 60
