---
- name: "[Prerequisites] - Disable SELinux"
  become: true
  selinux:
    state: disabled
  notify:
    - "restart_host"

- name: "[Prerequisites] - Increase system limits"
  become: true
  pam_limits:
    domain: "{{ dss_service_username }}"
    limit_item: "{{ item }}"
    limit_type: "-"
    value: 65536
  loop:
    - nofile
    - nproc

- name: "[Prerequisites] - Update all packages"
  become: true
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true

- name: "[Prerequisites] - Install required packages"
  become: true
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - acl
      - expat
      - git
      - nginx
      - unzip
      - zip
      - ncurses-compat-libs
      - java-1.8.0-openjdk
      - python2
      - python36
      - freetype
      - libgfortran
      - libgomp
      - python2-devel
      - python36-devel
      - "google-cloud-sdk"
      - "kubectl"
      - "epel-release"

- name: "[Prerequisites] - Install optional packages from epel"
  become: true
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "htop"


# User stuff

- name: "[Prerequisites] - Create '{{ dss_service_username }}' user"
  become: true
  ansible.builtin.user:
    name: "{{ dss_service_username }}"
    state: present

- name: "[Prerequisites] - Format DSS Data filesystem"
  become: true
  community.general.filesystem:
    dev: "{{ dss_data_dir_disk }}"
    fstype: "{{ dss_fs_data_type }}"

- name: "[Prerequisites] - Mount DSS Data filesystem"
  become: true
  ansible.posix.mount:
    fstype: "{{ dss_fs_data_type }}"
    path: "{{ dss_fs_data_mount_path }}"
    src: "{{ dss_data_dir_disk }}"
    opts: "defaults,acl"
    state: mounted

- name: "[Prerequisites] - Create public directories"
  become: true
  ansible.builtin.file:
    path: "{{ dss_install_target_dir }}"
    state: directory
    owner: "{{ dss_service_username }}"
    mode: 0711

- name: "[Prerequisites] - Create private directories"
  become: true
  ansible.builtin.file:
    path: "{{ dss_data_dir }}"
    state: directory
    owner: "{{ dss_service_username }}"
    mode: 0711
