---
plugin: gcp_compute
projects:
  - #<PROJECT_ID>#
auth_kind: serviceaccount
filters: name = "dss-instance"
service_account_file: "../terraform/gcp-credentials.json"
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
compose:

  ansible_user: "'#<SSH_USERNAME>#'"
  ansible_ssh_private_key_file: "'../terraform/cluster/.ssh/google_compute_engine'"
